### ISSUE TITLE
[Feature request] Leaderboard

### ISSUE THREAD

**Issue by qgorak** [MartinJeanne/ReactionTimer#1]
Hey,
adding a leaderboard can push players to improve their score and compare themselves

### Solution

Implement a backend with a database to record the user's score

**Comment by MartinJeanne** [comment]
Good idea ! 
I will look into that

**Comment by MartinJeanne** [comment]
Done ! I impleted a firestore database, for the moment users can save their scores online and see the scores of others.
There is no "leaderboard" for the moment, but it will eventualy come
